# Generated by Django 4.2.5 on 2023-09-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0004_alter_question_user_questionuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prueba",
        ),
        migrations.AddField(
            model_name="question",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="enabled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="choice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.choice",
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
